### ISSUE TITLE
[BUG]窗口控制按钮丢失

### ISSUE THREAD

**Issue by HumanMus1c** [FlysoftBeta/QQNTim-Plugins-Galaxy#4]
![image](https://github.com/Flysoft-Studio/QQNTim/assets/46023154/81237c44-7958-4100-9cb3-229fd8feb525)
------------------------------------------------------------------

测试了一下，是插件Mica背景有问题导致窗口控制按钮丢失。

------------------------------------------------------------------
![image](https://github.com/Flysoft-Studio/QQNTim/assets/46023154/68ccbfce-f2b6-4afb-89b4-4106d8ab2a96)

**Comment by HumanMus1c** [comment]
QQNTim终端日志:
[管理员 Windows PowerShell - log.txt](https://github.com/Flysoft-Studio/QQNTim-Plugins-Galaxy/files/12070181/Windows.PowerShell.-.log.txt)

**Comment by FlysoftBeta** [comment]
此仓库中的插件即将被弃用
